site_name: IBGE
site_url: https://github.com/Requisitos-de-Software/2025.1-Grupo05

repo_url: https://github.com/Requisitos-de-Software/2025.1-Grupo05
repo_name: 2025.1-IBGE

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Requisitos-de-Software/2025.1-Grupo05

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg



theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference

    # Palette toggle for high-contrast
    - media: "(prefers-color-scheme: high-contrast)"
      scheme: high-contrast
      toggle:
        icon: material/brightness-1
        name: Switch to system preference

  language: pt-BR
  favicon: assets/logo_ibge.png
  logo: assets/logo_ibge.png

  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking

extra_css:
  - assets/stylesheets/extra.css

nav:
  - Início : index.md
  - Atas :
    - Ata 1: atas/ata1.md
    - Ata 2: atas/ata2.md
    - Ata 3: atas/ata3.md
    - Ata 4: atas/ata4.md
    - Ata 5: atas/ata5.md 
    - Ata 6: atas/ata6.md 
    - Ata 7: atas/ata7.md 
  - Apresentações:
    - 1ª Entrega: 
      - Apresentação - 1ª entrega: aps/ap1/ap1.md
    - 2ª Entrega: 
      - Apresentação - 2ª entrega: aps/ap2/ap2.md

  - Planejamento : 
    - Aplicativo Escolhido: Planejamento/AplicativoEscolhido.md
    - Ferramentas: Planejamento/Ferramentas.md
    - Metodologia: Planejamento/Metodologia.md
    - Cronograma: Planejamento/Cronograma.md
    
  - Pré-rastreabilidade :
    - Rich Picture:
      - Aplicativos analisados: prerastreabilidade/rich-pic_alt.md
      - Aplicativo selecionado: prerastreabilidade/rich-picture.md
  - Verificação : 
    - Entrega 1:
      - Grupo: Verificacao/entrega1/lv1.md
      - Grupo +1: Verificacao/entrega1/etr1_gr+1.md
    - Entrega 2:
      - Grupo: Verificacao/entrega2/lv2.md
      - Grupo +1: Verificacao/entrega2/etr2_gr+1.md
  
  - Elicitação :
    - Usuários: 
      - Perfil do Usuário: elicitacao/usuarios/PerfilDoUsuario.md
      - Personas: elicitacao/usuarios//Personas.md
    - Técnicas analisadas: elicitacao/tecnicas.md
    - Técnicas selecionadas:
      - Análise de Interface: elicitacao/tecnicas_selecionadas/analise_interface.md
      - Brainstorming: elicitacao/tecnicas_selecionadas/brainstorming.md 
      - Introspecção: elicitacao/tecnicas_selecionadas/introspeccao.md
      - Questionário: elicitacao/tecnicas_selecionadas/questionario.md
      - Entrevista: elicitacao/tecnicas_selecionadas/entrevista.md
    - Requisitos Elicitados: elicitacao/Requisitos.md
    - Técnicas de Priorização analisadas: elicitacao/priorizacao_analisadas.md
    - Técnicas de Priorização selecionadas: 
      - First Things First: elicitacao/priorizacao_selecionadas/first_things_first.md
      - MoSCoW: elicitacao/priorizacao_selecionadas/moscow.md
      - $100: elicitacao/priorizacao_selecionadas/$100.md
      - Priorização por 3 Níveis: elicitacao/priorizacao_selecionadas/priorização_por_3_níveis.md
      - Votação: elicitacao/priorizacao_selecionadas/votacao.md
